language: php
matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - composer test

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage/coverage.clover ; fi
