language: php
matrix:
  include:
  - php: 7.3
  - php: 7.4
  - php: 8.0
  - php: 8.1

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - composer test

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '8.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage/coverage.clover ; fi
