language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

services:
  - mysql

cache:
  directories
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - composer install

script:
  - composer test
