language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

services:
  - mysql
  - memcached

cache:
  directories
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - composer install

script:
  - composer test

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage/coverage.clover ; fi
